-- Step 07E — B2B campaign metric antifraud/deduplication.
-- Keeps the existing RPC signature consumed by stores/adStore.ts.
-- Views: at most one counted event per authenticated user/campaign/hour.
-- Clicks: at most one counted event per authenticated user/campaign/15-minute bucket.

create schema if not exists private;

create table if not exists private.b2b_campaign_metric_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.b2b_campaigns(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  metric text not null check (metric in ('view', 'click')),
  event_bucket timestamptz not null,
  created_at timestamptz not null default now(),
  constraint b2b_campaign_metric_events_dedupe unique (campaign_id, user_id, metric, event_bucket)
);

create index if not exists b2b_campaign_metric_events_created_at_idx
  on private.b2b_campaign_metric_events (created_at);

revoke all on table private.b2b_campaign_metric_events from public, anon, authenticated;
revoke all on sequence private.b2b_campaign_metric_events_id_seq from public, anon, authenticated;

create or replace function public.increment_b2b_campaign_metric(
  p_campaign_id uuid,
  p_metric text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_bucket timestamptz;
  v_inserted integer := 0;
begin
  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  if p_metric not in ('view', 'click') then
    raise exception 'invalid campaign metric';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_user_id
      and p.status = 'active'::public.profile_status
  ) then
    raise exception 'inactive profile';
  end if;

  -- Fail closed for nonexistent, paused or expired campaigns.
  if not exists (
    select 1
    from public.b2b_campaigns c
    where c.id = p_campaign_id
      and c.status = 'approved'
      and c.created_at <= now()
      and c.created_at + make_interval(hours => greatest(coalesce(c.duration_hours, 24), 1)) > now()
  ) then
    return;
  end if;

  v_bucket := case
    when p_metric = 'view' then date_trunc('hour', now())
    else date_trunc('hour', now())
       + (floor(extract(minute from now()) / 15)::int * interval '15 minutes')
  end;

  insert into private.b2b_campaign_metric_events (
    campaign_id,
    user_id,
    metric,
    event_bucket
  )
  values (
    p_campaign_id,
    v_user_id,
    p_metric,
    v_bucket
  )
  on conflict (campaign_id, user_id, metric, event_bucket) do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return;
  end if;

  if p_metric = 'view' then
    update public.b2b_campaigns
    set views_count = views_count + 1
    where id = p_campaign_id;
  else
    update public.b2b_campaigns
    set clicks_count = clicks_count + 1
    where id = p_campaign_id;
  end if;
end;
$$;

revoke all on function public.increment_b2b_campaign_metric(uuid, text) from public, anon;
grant execute on function public.increment_b2b_campaign_metric(uuid, text) to authenticated;
