-- Step 07G — Video view antifraud/deduplication.
-- Keeps public.increment_video_views(integer) compatible with existing frontend calls.
-- Counts at most one view per authenticated user/video/hour.

create schema if not exists private;

create table if not exists private.video_view_events (
  id bigint generated by default as identity primary key,
  video_id integer not null references public.videos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_bucket timestamptz not null,
  created_at timestamptz not null default now(),
  constraint video_view_events_dedupe unique (video_id, user_id, event_bucket)
);

create index if not exists video_view_events_user_id_idx
  on private.video_view_events (user_id);

create index if not exists video_view_events_created_at_idx
  on private.video_view_events (created_at);

-- Also cover the user FK introduced by the previous B2B metric ledger.
create index if not exists b2b_campaign_metric_events_user_id_idx
  on private.b2b_campaign_metric_events (user_id);

revoke all on table private.video_view_events from public, anon, authenticated;
revoke all on sequence private.video_view_events_id_seq from public, anon, authenticated;

create or replace function public.increment_video_views(video_id integer)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_inserted integer := 0;
begin
  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_user_id
      and p.status = 'active'::public.profile_status
  ) then
    raise exception 'inactive profile';
  end if;

  if not exists (
    select 1 from public.videos v where v.id = video_id
  ) then
    return;
  end if;

  insert into private.video_view_events (
    video_id,
    user_id,
    event_bucket
  )
  values (
    video_id,
    v_user_id,
    date_trunc('hour', now())
  )
  on conflict (video_id, user_id, event_bucket) do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return;
  end if;

  update public.videos
  set views_count = coalesce(views_count, 0) + 1
  where id = video_id;
end;
$$;

revoke all on function public.increment_video_views(integer) from public, anon;
grant execute on function public.increment_video_views(integer) to authenticated;
