-- Launch P0: private album delivery must be server-authorized and signed.

create or replace function public.open_private_album_server_v1(
  p_actor_id uuid,
  p_album_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_owner uuid;
  v_access public.private_album_access%rowtype;
  v_album jsonb;
  v_photos jsonb;
  v_access_json jsonb := jsonb_build_object(
    'is_view_once', false,
    'expires_at', null,
    'consumed_at', null
  );
begin
  if p_actor_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  select user_id into v_owner
  from public.private_albums
  where id = p_album_id;

  if v_owner is null then
    raise exception 'album_not_found' using errcode = 'P0002';
  end if;

  if p_actor_id <> v_owner then
    select paa.* into v_access
    from public.private_album_access paa
    where paa.requester_id = p_actor_id
      and paa.owner_id = v_owner
      and paa.status = 'granted'
      and (paa.album_id = p_album_id or paa.album_id is null)
      and (paa.expires_at is null or paa.expires_at > now())
      and paa.consumed_at is null
    order by (paa.album_id is null), paa.id desc
    limit 1
    for update;

    if v_access.id is null then
      raise exception 'album_access_denied' using errcode = '42501';
    end if;

    v_access_json := jsonb_build_object(
      'is_view_once', coalesce(v_access.is_view_once, false),
      'expires_at', v_access.expires_at,
      'consumed_at', v_access.consumed_at
    );

    if v_access.is_view_once then
      update public.private_album_access
      set consumed_at = now(), updated_at = now()
      where id = v_access.id and consumed_at is null;

      if not found then
        raise exception 'album_access_consumed' using errcode = '42501';
      end if;
    end if;
  end if;

  select to_jsonb(pa) into v_album
  from public.private_albums pa
  where pa.id = p_album_id;

  select coalesce(jsonb_agg(to_jsonb(pap) order by pap.created_at, pap.id), '[]'::jsonb)
    into v_photos
  from public.private_album_photos pap
  where pap.album_id = p_album_id;

  return v_album || jsonb_build_object(
    'private_album_photos', v_photos,
    '_access', v_access_json
  );
end;
$$;

revoke all on function public.open_private_album_server_v1(uuid, integer) from public;
revoke all on function public.open_private_album_server_v1(uuid, integer) from anon;
revoke all on function public.open_private_album_server_v1(uuid, integer) from authenticated;
grant execute on function public.open_private_album_server_v1(uuid, integer) to service_role;

-- Requesters no longer receive direct Storage SELECT. Authorized delivery happens
-- through a short-lived signed URL generated by the server after album authorization.
drop policy if exists private_media_select_authorized on storage.objects;
drop policy if exists private_media_select_owner on storage.objects;
create policy private_media_select_owner
on storage.objects
for select
to authenticated
using (
  bucket_id = 'private_media'
  and split_part(name, '/', 1) = (select auth.uid())::text
);
