-- Step 05C — Notification delivery idempotency
-- Private persistence + service-role-only RPCs used by the Notification Engine.

begin;

create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

grant usage on schema private to postgres;

create table if not exists private.notification_deliveries (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('message', 'wink', 'album_request')),
  event_id bigint not null,
  actor_id uuid not null,
  recipient_id uuid not null,
  status text not null default 'claimed' check (status in ('claimed', 'sent', 'skipped', 'failed')),
  error_code text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (event_type, event_id)
);

create index if not exists notification_deliveries_recipient_created_idx
  on private.notification_deliveries (recipient_id, created_at desc);

revoke all on table private.notification_deliveries from public;
revoke all on table private.notification_deliveries from anon;
revoke all on table private.notification_deliveries from authenticated;

create or replace function public.claim_notification_delivery(
  p_event_type text,
  p_event_id bigint,
  p_actor_id uuid,
  p_recipient_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, private, pg_temp
as $function$
declare
  v_rows integer;
begin
  if p_event_type not in ('message', 'wink', 'album_request') then
    raise exception 'Unsupported notification event type.' using errcode = '22023';
  end if;

  if p_event_id is null or p_actor_id is null or p_recipient_id is null then
    raise exception 'Notification delivery identity is incomplete.' using errcode = '22004';
  end if;

  if p_actor_id = p_recipient_id then
    raise exception 'Notification actor and recipient must differ.' using errcode = '22023';
  end if;

  insert into private.notification_deliveries (
    event_type,
    event_id,
    actor_id,
    recipient_id,
    status
  )
  values (
    p_event_type,
    p_event_id,
    p_actor_id,
    p_recipient_id,
    'claimed'
  )
  on conflict (event_type, event_id) do nothing;

  get diagnostics v_rows = row_count;
  return v_rows = 1;
end;
$function$;

create or replace function public.finish_notification_delivery(
  p_event_type text,
  p_event_id bigint,
  p_status text,
  p_error_code text default null
)
returns void
language plpgsql
security definer
set search_path = public, private, pg_temp
as $function$
begin
  if p_status not in ('sent', 'skipped', 'failed') then
    raise exception 'Invalid notification delivery status.' using errcode = '22023';
  end if;

  update private.notification_deliveries
  set
    status = p_status,
    error_code = left(p_error_code, 160),
    completed_at = now()
  where event_type = p_event_type
    and event_id = p_event_id;
end;
$function$;

revoke execute on function public.claim_notification_delivery(text, bigint, uuid, uuid) from public;
revoke execute on function public.claim_notification_delivery(text, bigint, uuid, uuid) from anon;
revoke execute on function public.claim_notification_delivery(text, bigint, uuid, uuid) from authenticated;
grant execute on function public.claim_notification_delivery(text, bigint, uuid, uuid) to service_role;

revoke execute on function public.finish_notification_delivery(text, bigint, text, text) from public;
revoke execute on function public.finish_notification_delivery(text, bigint, text, text) from anon;
revoke execute on function public.finish_notification_delivery(text, bigint, text, text) from authenticated;
grant execute on function public.finish_notification_delivery(text, bigint, text, text) to service_role;

commit;
