create table if not exists public.report_chat_evidence (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  conversation_id bigint not null,
  source_message_id bigint not null,
  sender_id uuid not null,
  sent_at timestamptz not null,
  content_snapshot text null,
  image_path_snapshot text null,
  is_view_once boolean not null default false,
  captured_at timestamptz not null default now(),
  unique(report_id, source_message_id)
);

create index if not exists report_chat_evidence_report_idx on public.report_chat_evidence(report_id, captured_at);
alter table public.report_chat_evidence enable row level security;

create or replace function public.get_report_chat_candidates_v1(
  p_reported_id uuid,
  p_limit integer default 100
)
returns table(
  id bigint,
  sender_id uuid,
  content text,
  image_url text,
  is_view_once boolean,
  viewed_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path='pg_catalog','public','pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_conversation_id bigint;
  v_limit integer := greatest(1, least(coalesce(p_limit,100), 150));
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not private.current_user_session_allowed() then raise exception 'session_not_allowed' using errcode='42501'; end if;
  if p_reported_id is null or p_reported_id=v_uid then raise exception 'invalid_reported_user' using errcode='22023'; end if;

  select cp.conversation_id into v_conversation_id
  from public.conversation_participants cp
  where cp.user_id in (v_uid,p_reported_id)
  group by cp.conversation_id
  having count(distinct cp.user_id)=2
     and (select count(*) from public.conversation_participants all_cp where all_cp.conversation_id=cp.conversation_id)=2
  order by cp.conversation_id desc
  limit 1;

  if v_conversation_id is null then return; end if;

  return query
  select m.id,m.sender_id,m.content,m.image_url,coalesce(m.is_view_once,false),m.viewed_at,m.created_at
  from public.messages m
  where m.conversation_id=v_conversation_id
  order by m.created_at desc
  limit v_limit;
end;
$$;

create or replace function public.report_attach_chat_evidence_v1(
  p_report_id bigint,
  p_message_ids bigint[]
)
returns integer
language plpgsql
security definer
set search_path='pg_catalog','public','pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_report public.reports%rowtype;
  v_conversation_id bigint;
  v_count integer;
  v_unique_count integer;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not private.current_user_session_allowed() then raise exception 'session_not_allowed' using errcode='42501'; end if;
  if p_report_id is null then raise exception 'report_required' using errcode='22023'; end if;
  if p_message_ids is null or cardinality(p_message_ids)<1 or cardinality(p_message_ids)>12 then
    raise exception 'select_between_1_and_12_messages' using errcode='22023';
  end if;

  select * into v_report from public.reports r
  where r.id=p_report_id and r.reporter_id=v_uid and r.status in ('open','reviewing');
  if not found then raise exception 'report_not_available' using errcode='42501'; end if;

  select count(distinct x) into v_unique_count from unnest(p_message_ids) x;
  if v_unique_count <> cardinality(p_message_ids) then raise exception 'duplicate_message_ids' using errcode='22023'; end if;

  select min(m.conversation_id), count(*) into v_conversation_id, v_count
  from public.messages m
  where m.id=any(p_message_ids);
  if v_count<>cardinality(p_message_ids) then raise exception 'message_not_found' using errcode='P0002'; end if;
  if exists(select 1 from public.messages m where m.id=any(p_message_ids) and m.conversation_id<>v_conversation_id) then
    raise exception 'messages_must_share_conversation' using errcode='22023';
  end if;

  if not exists(select 1 from public.conversation_participants cp where cp.conversation_id=v_conversation_id and cp.user_id=v_uid)
     or not exists(select 1 from public.conversation_participants cp where cp.conversation_id=v_conversation_id and cp.user_id=v_report.reported_id)
     or (select count(*) from public.conversation_participants cp where cp.conversation_id=v_conversation_id)<>2 then
    raise exception 'conversation_not_eligible' using errcode='42501';
  end if;

  insert into public.report_chat_evidence(
    report_id,reporter_id,conversation_id,source_message_id,sender_id,sent_at,
    content_snapshot,image_path_snapshot,is_view_once
  )
  select v_report.id,v_uid,m.conversation_id,m.id,m.sender_id,m.created_at,
         left(m.content,4000),m.image_url,coalesce(m.is_view_once,false)
  from public.messages m
  where m.id=any(p_message_ids)
  on conflict(report_id,source_message_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.get_report_chat_candidates_v1(uuid,integer) from public,anon;
revoke all on function public.report_attach_chat_evidence_v1(bigint,bigint[]) from public,anon;
grant execute on function public.get_report_chat_candidates_v1(uuid,integer) to authenticated;
grant execute on function public.report_attach_chat_evidence_v1(bigint,bigint[]) to authenticated;

revoke all on public.report_chat_evidence from anon, authenticated;
grant select,insert,update,delete on public.report_chat_evidence to service_role;
